"""Add ai_reflection column in progress_logs table

Revision ID: 18381b41bb1c
Revises: 94dff1cc9cdd
Create Date: 2026-02-01 15:00:49.145863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18381b41bb1c"
down_revision: Union[str, Sequence[str], None] = "94dff1cc9cdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("progress_logs", sa.Column("ai_reflection", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("progress_logs", "ai_reflection")
    # ### end Alembic commands ###
