"""remove learning_sources from resolutions

Revision ID: 323f38f90688
Revises: 001
Create Date: 2026-01-27 22:51:33.732494

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "323f38f90688"
down_revision: Union[str, Sequence[str], None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resolutions", "learning_sources")
    op.create_index(
        op.f("ix_weekly_reflections_resolution_id"),
        "weekly_reflections",
        ["resolution_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_weekly_reflections_resolution_id"), table_name="weekly_reflections"
    )
    op.add_column(
        "resolutions",
        sa.Column(
            "learning_sources",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
