"""Add streak groups shield and pause features

Revision ID: 48d77bca4d63
Revises: c95ac29675b8
Create Date: 2026-02-05 21:14:37.950959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d77bca4d63'
down_revision: Union[str, Sequence[str], None] = 'c95ac29675b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_queue_id'), 'email_queue', ['id'], unique=False)
    op.create_index(op.f('ix_email_queue_user_id'), 'email_queue', ['user_id'], unique=False)
    op.create_table('streak_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streak_groups_created_by'), 'streak_groups', ['created_by'], unique=False)
    op.create_index(op.f('ix_streak_groups_id'), 'streak_groups', ['id'], unique=False)
    op.create_table('streak_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['streak_groups.id'], ),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streak_group_members_group_id'), 'streak_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_streak_group_members_id'), 'streak_group_members', ['id'], unique=False)
    op.create_index(op.f('ix_streak_group_members_resolution_id'), 'streak_group_members', ['resolution_id'], unique=False)
    op.create_index(op.f('ix_streak_group_members_user_id'), 'streak_group_members', ['user_id'], unique=False)
    op.drop_constraint(op.f('north_star_goals_resolution_id_key'), 'north_star_goals', type_='unique')
    op.add_column('streaks', sa.Column('shield_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('streaks', sa.Column('consecutive_checkins', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_email_preferences', sa.Column('is_paused', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_email_preferences', sa.Column('paused_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_user_email_preferences_schedule'), table_name='user_email_preferences')
    op.create_index(op.f('ix_user_email_preferences_id'), 'user_email_preferences', ['id'], unique=False)
    op.drop_constraint(op.f('user_email_preferences_user_id_fkey'), 'user_email_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'user_email_preferences', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_email_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('user_email_preferences_user_id_fkey'), 'user_email_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_email_preferences_id'), table_name='user_email_preferences')
    op.create_index(op.f('ix_user_email_preferences_schedule'), 'user_email_preferences', ['email_opt_in', 'timezone', 'preferred_hour'], unique=False)
    op.drop_column('user_email_preferences', 'paused_at')
    op.drop_column('user_email_preferences', 'is_paused')
    op.drop_column('streaks', 'consecutive_checkins')
    op.drop_column('streaks', 'shield_count')
    op.create_unique_constraint(op.f('north_star_goals_resolution_id_key'), 'north_star_goals', ['resolution_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_streak_group_members_user_id'), table_name='streak_group_members')
    op.drop_index(op.f('ix_streak_group_members_resolution_id'), table_name='streak_group_members')
    op.drop_index(op.f('ix_streak_group_members_id'), table_name='streak_group_members')
    op.drop_index(op.f('ix_streak_group_members_group_id'), table_name='streak_group_members')
    op.drop_table('streak_group_members')
    op.drop_index(op.f('ix_streak_groups_id'), table_name='streak_groups')
    op.drop_index(op.f('ix_streak_groups_created_by'), table_name='streak_groups')
    op.drop_table('streak_groups')
    op.drop_index(op.f('ix_email_queue_user_id'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_id'), table_name='email_queue')
    op.drop_table('email_queue')
    # ### end Alembic commands ###
