"""Add progress_percentage column in milestones table

Revision ID: 761f726bf4f0
Revises: 48d77bca4d63
Create Date: 2026-02-06 21:42:55.330268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761f726bf4f0'
down_revision: Union[str, Sequence[str], None] = '48d77bca4d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('progress_percentage', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'progress_percentage')
    # ### end Alembic commands ###
